### ISSUE TITLE
Todo List for Release

### ISSUE THREAD

**Issue by nrayburn-tech** [nrayburn-tech/node-http-proxy#5]
List of things that need to be done, so that a release can be made. The list is a WIP, and will be checked off/items added as changes are made.

Beta
- [x] Figure out a package name, preferably one scoped under an organization (which also needs a name figured out).
- [ ] Update changelog.md and upgrading.md
- [ ] Update readme with any usage changes.
- [x] Update package.json, code_of_conduct.md, and license.md if needed.
- [ ] Leave comments on issues the original repo to let others know this alternative exists (and is in beta).
- [x] Rename repo from 'node-http-proxy' to 'http-proxy'.

Release
- [ ] Migrate examples to TypeScript
- [ ] Migrate tests to TypeScript
- [ ] Review and possibly implement anything necessary from https://github.com/nrayburn-tech/node-http-proxy/blob/abb105ada575707a7ac8f601b1c96e7135a78b0e/lib/index.ts#L32
- [x] Setup dependabot (or similar) to manage updates (primarily security updates)

**Comment by nrayburn-tech** [comment]
> Figure out a package name, preferably one scoped under an organization (which also needs a name figured out).

Created 'nrayburn-tech' as an organization for NPM, it's an easy choice for now and makes since with the repo being published under the 'nrayburn-tech' Github account.

**Comment by nrayburn-tech** [comment]
Published an alpha to npm, https://www.npmjs.com/package/@nrayburn-tech/http-proxy.

**Comment by haf** [comment]
Maybe take the opportunity to sync the name of the repo with the name of the node module.
